name: ytdatagen
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.24.0
  - opencv-python>=4.8.0
  - requests>=2.31.0
  - pip
  - pip:
    - yt-dlp>=2023.7.6
    - pathlib2>=2.3.7
    - PyYAML>=6.0
    - reportlab>=4.0.0
    - tqdm>=4.65.0
    - ultralytics>=8.3.0
    - pycocotools>=2.0.7
 #   - fiftyone>=1.7.2